name: Release

on:
  workflow_dispatch:
  push: { tags: ["v*.*.*"] }

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate
        run: cmake -B ./build

      - name: Build
        run: cmake --build ./build --target PACKAGE --config Release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/package/run_hidden*
